### ISSUE TITLE
how to get email after authentication 

### ISSUE THREAD

**Issue by myselfgaurav** [mptre/php-soundcloud#32]
below is code i am using for authentiocation:

require_once 'soundcloud/Soundcloud.php';

$soundcloud = new Services_Soundcloud($clientId, $clientSecret, $callback);
try {
   $accessToken = $soundcloud->accessToken($_GET['code']);
} catch (Services_Soundcloud_Invalid_Http_Response_Code_Exception $e) {
    exit($e->getMessage());
}
try {
    $me = json_decode($soundcloud->get('me'), true);
} catch (Services_Soundcloud_Invalid_Http_Response_Code_Exception $e) {
    exit($e->getMessage());
}

$user_data = array(
                'access_token' => $accessToken['access_token'],
                'id' => $me['id'],
                'username' => $me['username'],
                'name' => $me['full_name'],
				'email' => $me['email'],
                'avatar' => $me['avatar_url']
            );

but it does not return email how to get email value

**Comment by glenscott** [comment]
A user's email address is not surfaced by the SoundCloud API, so you cannot retrieve it.

The fields that are available to get from an authenticated user are detailed here:

https://developers.soundcloud.com/docs/api/reference#me
