### ISSUE TITLE
can't use but one redirect url

### ISSUE THREAD

**Issue by teo1978** [mptre/php-soundcloud#36]
This is probably a bug in the API itself rather than in the SDK, but there doesn't seem to be a bugtracker for the API. I hope they are maintained by the same people or that you can report the issue upstream to the API maintainers.

Following the guide at https://developers.soundcloud.com/docs#authentication
If I pass a redirect url as parameter to the Services_Soundcloud constructor that is not the same url defined at https://soundcloud.com/you/apps/MY_APP/edit, then I get the error: 
> error=redirect_uri_mismatch&error_description=The+redirection+URI+provided+does+not+match+a+pre-registered+value.

That is nonsense. 
1) If only one fixed redirect url can use, then what the hell is the third parameter of the constructor for?
2) The api MUST allow to use an arbitrary url. Having one fixed return url for authentication is ridiculous (and a restriction that no other social network API has), as it makes it impossible to have a login url in any arbitrary page and have the user return to the page where he was before logging in. That makes the api unusable. If that is by design, it's a ridiculously stupid design.

**Comment by glenscott** [comment]
I agree with you about the redirect URL:  it does seem rather pointless that you have to include it in the request given that it is a static URL.

The API _does not_ allow an arbitrary URL.  As you noted, this is unlike most other oAuth-backed social network API's.  The workaround I can recommend is using the `state` parameter to pass back your return URL.  You can do this when generating the authorization URL like this:

````
                $client->getAuthorizeUrl(
                    array(
                        'state' => 'http://example.com/return'
                    )
````

You'll get the state parameter added to the static redirect URL.  For example, if you set your redirect URL to http://example.com/callback then SoundCloud will redirect an authenticated user to http://example.com/callback?state=http://example.com/return

Your callback script will need to look for the state GET parameter, and redirect using it.

Reference to the state parameter:

https://developers.soundcloud.com/docs/api/reference#connect

**Comment by teo1978** [comment]
I see, then it is the API itself that has been conceived by a monkey
