### ISSUE TITLE
The requested package mptre/php-soundcloud could not be found in any version

### ISSUE THREAD

**Issue by rohitkhatri** [mptre/php-soundcloud#42]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mptre/php-soundcloud could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by glenscott** [comment]
This looks like a composer problem with a package that is not under my control.  Can you clarify the steps you are taking that lead to this issue?

**Comment by rohitkhatri** [comment]
I'm working on laravel, and there is a global composer file where I put "mptre/php-soundcloud": "2.*" in require array. What did I do wrong, please let me know.

**Comment by glenscott** [comment]
There is no Composer package named "mptre/php-soundcloud"

Available SoundCloud packages can be seen here:

https://packagist.org/search/?q=soundcloud

I believe "ise/php-soundcloud" is what you are looking for.

**Comment by rohitkhatri** [comment]
Thanks it worked.
