### ISSUE TITLE
/users/{id}/followers returns 404

### ISSUE THREAD

**Issue by faizanahmad** [mptre/php-soundcloud#44]
Since last few days following api calls returns 404 error. 
`$client->get('users/{id}/followers')`
Anyone know what's causing the issue or  how to fix it?

**Comment by MrWalakala** [comment]
I have the same issue on every post "me/" call

**Comment by faizanahmad** [comment]
@MrWalakala did you figure it out what's wrong?

**Comment by faizanahmad** [comment]
SoundCloud has deprecated v1 version of API so you have to comment out line 792 of Services_Soundcloud.php 
`//$url .= ($includeVersion) ? 'v' . self::$_apiVersion . '/' : '';`
